[DEFAULT]
; /home/bacci/COMPACT
    ; df_pairs_path = /Users/bacci/GitHub/COMPACT/data/train_test/train_pairs.csv
    df_pairs_path = data/train_test/bin_train_pairs_new.csv
    df_debug_pairs_path = data/interim/debug_pairs_df.csv
    df_strings_path = data/train_test/bin_train0_new.csv
    filters_path = data/filters/sub-filters.csv
    advanced_filters_path = data/filters/bitmask_patterns_sliding_window.csv

[MULTI-PROCESSING]
    max_workers = 1

